"""create initial tables

Revision ID: 26d30a84516e
Revises: 
Create Date: 2026-06-20 00:21:44.487377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d30a84516e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('camp_packages',
    sa.Column('camp_package_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('session_count', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('camp_package_id')
    )
    op.create_index(op.f('ix_camp_packages_camp_package_id'), 'camp_packages', ['camp_package_id'], unique=False)
    op.create_index(op.f('ix_camp_packages_organization_id'), 'camp_packages', ['organization_id'], unique=False)
    op.create_table('organization_users',
    sa.Column('organization_user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('organization_user_id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_user')
    )
    op.create_index(op.f('ix_organization_users_organization_user_id'), 'organization_users', ['organization_user_id'], unique=False)
    op.create_table('participants',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('participant_id')
    )
    op.create_index(op.f('ix_participants_organization_id'), 'participants', ['organization_id'], unique=False)
    op.create_index(op.f('ix_participants_participant_id'), 'participants', ['participant_id'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_organization_id'), 'sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=False)
    op.create_table('waivers',
    sa.Column('waiver_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('waiver_name', sa.String(length=150), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('waiver_id')
    )
    op.create_index(op.f('ix_waivers_organization_id'), 'waivers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_waivers_waiver_id'), 'waivers', ['waiver_id'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('emergency_contact_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=150), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.participant_id'], ),
    sa.PrimaryKeyConstraint('emergency_contact_id')
    )
    op.create_index(op.f('ix_emergency_contacts_emergency_contact_id'), 'emergency_contacts', ['emergency_contact_id'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_participant_id'), 'emergency_contacts', ['participant_id'], unique=False)
    op.create_table('guardian_participants',
    sa.Column('guardian_participant_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('guardian_user_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['guardian_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.participant_id'], ),
    sa.PrimaryKeyConstraint('guardian_participant_id'),
    sa.UniqueConstraint('organization_id', 'guardian_user_id', 'participant_id', name='uq_guardian_participant')
    )
    op.create_index(op.f('ix_guardian_participants_guardian_participant_id'), 'guardian_participants', ['guardian_participant_id'], unique=False)
    op.create_index(op.f('ix_guardian_participants_guardian_user_id'), 'guardian_participants', ['guardian_user_id'], unique=False)
    op.create_index(op.f('ix_guardian_participants_organization_id'), 'guardian_participants', ['organization_id'], unique=False)
    op.create_index(op.f('ix_guardian_participants_participant_id'), 'guardian_participants', ['participant_id'], unique=False)
    op.create_table('participant_packages',
    sa.Column('participant_package_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('camp_package_id', sa.Integer(), nullable=False),
    sa.Column('package_name_at_purchase', sa.String(length=100), nullable=False),
    sa.Column('price_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('remaining_sessions', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['camp_package_id'], ['camp_packages.camp_package_id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.participant_id'], ),
    sa.PrimaryKeyConstraint('participant_package_id')
    )
    op.create_index(op.f('ix_participant_packages_camp_package_id'), 'participant_packages', ['camp_package_id'], unique=False)
    op.create_index(op.f('ix_participant_packages_participant_id'), 'participant_packages', ['participant_id'], unique=False)
    op.create_index(op.f('ix_participant_packages_participant_package_id'), 'participant_packages', ['participant_package_id'], unique=False)
    op.create_table('signed_waivers',
    sa.Column('signed_waiver_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('waiver_id', sa.Integer(), nullable=False),
    sa.Column('signed_file_s3_key', sa.String(length=500), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.participant_id'], ),
    sa.ForeignKeyConstraint(['waiver_id'], ['waivers.waiver_id'], ),
    sa.PrimaryKeyConstraint('signed_waiver_id'),
    sa.UniqueConstraint('participant_id', 'waiver_id', name='uq_participant_waiver')
    )
    op.create_index(op.f('ix_signed_waivers_participant_id'), 'signed_waivers', ['participant_id'], unique=False)
    op.create_index(op.f('ix_signed_waivers_signed_waiver_id'), 'signed_waivers', ['signed_waiver_id'], unique=False)
    op.create_index(op.f('ix_signed_waivers_waiver_id'), 'signed_waivers', ['waiver_id'], unique=False)
    op.create_table('check_ins',
    sa.Column('check_in_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant_package_id', sa.Integer(), nullable=False),
    sa.Column('checked_in_by_user_id', sa.Integer(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['checked_in_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.participant_id'], ),
    sa.ForeignKeyConstraint(['participant_package_id'], ['participant_packages.participant_package_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    sa.PrimaryKeyConstraint('check_in_id'),
    sa.UniqueConstraint('participant_id', 'session_id', name='uq_participant_session_check_in')
    )
    op.create_index(op.f('ix_check_ins_check_in_id'), 'check_ins', ['check_in_id'], unique=False)
    op.create_index(op.f('ix_check_ins_checked_in_by_user_id'), 'check_ins', ['checked_in_by_user_id'], unique=False)
    op.create_index(op.f('ix_check_ins_participant_id'), 'check_ins', ['participant_id'], unique=False)
    op.create_index(op.f('ix_check_ins_participant_package_id'), 'check_ins', ['participant_package_id'], unique=False)
    op.create_index(op.f('ix_check_ins_session_id'), 'check_ins', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_ins_session_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_participant_package_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_participant_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_checked_in_by_user_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_check_in_id'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_signed_waivers_waiver_id'), table_name='signed_waivers')
    op.drop_index(op.f('ix_signed_waivers_signed_waiver_id'), table_name='signed_waivers')
    op.drop_index(op.f('ix_signed_waivers_participant_id'), table_name='signed_waivers')
    op.drop_table('signed_waivers')
    op.drop_index(op.f('ix_participant_packages_participant_package_id'), table_name='participant_packages')
    op.drop_index(op.f('ix_participant_packages_participant_id'), table_name='participant_packages')
    op.drop_index(op.f('ix_participant_packages_camp_package_id'), table_name='participant_packages')
    op.drop_table('participant_packages')
    op.drop_index(op.f('ix_guardian_participants_participant_id'), table_name='guardian_participants')
    op.drop_index(op.f('ix_guardian_participants_organization_id'), table_name='guardian_participants')
    op.drop_index(op.f('ix_guardian_participants_guardian_user_id'), table_name='guardian_participants')
    op.drop_index(op.f('ix_guardian_participants_guardian_participant_id'), table_name='guardian_participants')
    op.drop_table('guardian_participants')
    op.drop_index(op.f('ix_emergency_contacts_participant_id'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_emergency_contact_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_waivers_waiver_id'), table_name='waivers')
    op.drop_index(op.f('ix_waivers_organization_id'), table_name='waivers')
    op.drop_table('waivers')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_organization_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_participants_participant_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_organization_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_organization_users_organization_user_id'), table_name='organization_users')
    op.drop_table('organization_users')
    op.drop_index(op.f('ix_camp_packages_organization_id'), table_name='camp_packages')
    op.drop_index(op.f('ix_camp_packages_camp_package_id'), table_name='camp_packages')
    op.drop_table('camp_packages')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
